import type { ReactNode } from 'react';
import { Badge, SectionLabel } from '@/components/ui/primitives';
import type { ClaimBasis, ResearchNote, ResearchSource } from '@/lib/research/qualitative/types';

/* ==================================================================
   Rendering qualitative research.

   The point of these components is that a reader never has to guess
   which kind of claim they are looking at. Every note carries a basis
   chip, and the chip is not decoration: a published figure and an
   analyst's argument are different things and the product says so.
   ================================================================== */

const BASIS_LABEL: Record<ClaimBasis, string> = {
  STRUCTURAL: 'Structural',
  REPORTED: 'Reported',
  INTERPRETATION: 'Interpretation',
};

const BASIS_TONE: Record<ClaimBasis, 'outline' | 'accent' | 'brass'> = {
  STRUCTURAL: 'outline',
  REPORTED: 'accent',
  INTERPRETATION: 'brass',
};

const BASIS_HELP: Record<ClaimBasis, string> = {
  STRUCTURAL: 'How the industry or company is built. Checkable and slow to change.',
  REPORTED: 'A figure or fact published by the company, a regulator or a named source.',
  INTERPRETATION: 'An argument built on the above. It can be wrong without anything being false.',
};

export function BasisChip({ basis }: { basis: ClaimBasis }) {
  return (
    <Badge tone={BASIS_TONE[basis]} title={BASIS_HELP[basis]}>
      {BASIS_LABEL[basis]}
    </Badge>
  );
}

/** A research paragraph with its basis beside the heading. */
export function Note({ note }: { note: ResearchNote }) {
  return (
    <div className="border-l-2 border-line pl-3">
      <div className="flex items-start justify-between gap-2">
        <h4 className="text-sm font-semibold text-ink">{note.heading}</h4>
        <BasisChip basis={note.basis} />
      </div>
      <p className="mt-1 text-xs leading-relaxed text-ink-2">{note.body}</p>
    </div>
  );
}

export function NoteList({ notes, empty }: { notes: ResearchNote[]; empty?: string }) {
  if (!notes.length) {
    return <p className="text-xs text-ink-3">{empty ?? 'Nothing recorded.'}</p>;
  }
  return (
    <div className="space-y-3">
      {notes.map((n) => <Note key={n.heading} note={n} />)}
    </div>
  );
}

/** A labelled list of short strings — barriers, protections, requirements. */
export function Bullets({ label, items, tone }: { label: string; items: string[]; tone?: 'pos' | 'neg' }) {
  if (!items.length) return null;
  const marker = tone === 'neg' ? 'text-neg' : tone === 'pos' ? 'text-pos' : 'text-ink-4';
  return (
    <div>
      <SectionLabel>{label}</SectionLabel>
      <ul className="space-y-1">
        {items.map((it) => (
          <li key={it} className="flex gap-2 text-xs leading-relaxed text-ink-2">
            <span className={marker} aria-hidden>—</span>
            <span className="min-w-0">{it}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

/**
 * Where the research came from, and a standing reminder of what it is not.
 *
 * The quantitative model in this product is generated by the simulated data
 * provider. This prose is about real companies and real regulators. Showing
 * them on the same screen without saying which is which would be the exact
 * confusion the guardrails exist to prevent.
 */
export function SourceFooter({ asOf, sources }: { asOf: string; sources: ResearchSource[] }) {
  return (
    <div className="mt-4 border-t border-line pt-3">
      <div className="flex flex-wrap items-center gap-2">
        <SectionLabel className="mb-0">Researched</SectionLabel>
        <span className="text-xs text-ink-3">as of {asOf}</span>
      </div>
      <ul className="mt-2 space-y-1">
        {sources.map((s) => (
          <li key={s.url} className="text-xs leading-relaxed">
            <a
              href={s.url} target="_blank" rel="noreferrer noopener"
              className="text-accent hover:underline focus-ring"
            >
              {s.label}
            </a>
          </li>
        ))}
      </ul>
      <p className="mt-2 text-2xs leading-relaxed text-ink-4">
        Qualitative research on the real company and industry, from the sources above. The financial
        statements, prices and model outputs elsewhere in this workspace are generated by the simulated
        data provider and are not market data.
      </p>
    </div>
  );
}

export function DirectionBadge({ direction }: { direction: 'TAILWIND' | 'HEADWIND' | 'MIXED' }) {
  const tone = direction === 'TAILWIND' ? 'pos' : direction === 'HEADWIND' ? 'neg' : 'warn';
  const label = direction === 'TAILWIND' ? 'Tailwind' : direction === 'HEADWIND' ? 'Headwind' : 'Mixed';
  return <Badge tone={tone}>{label}</Badge>;
}

export function KeyValue({ label, children }: { label: string; children: ReactNode }) {
  return (
    <div>
      <SectionLabel>{label}</SectionLabel>
      <div className="text-xs leading-relaxed text-ink-2">{children}</div>
    </div>
  );
}
